trainer:
  epochs: 1000
  verbose: true

model:
  model_type: "efficientnet"  # Can be "resnet" or "efficientnet"
  initial_filters: 30
  multiplier: 1.5

optimizer:
  learning_rate: 0.001
  weight_decay: 0.0001

preprocessing:
  use_full_preprocessing: true
  # If true, equivalent to:
  # preprocessing_steps:
  #   - "remove_background"
  #   - "to_grayscale"
  #   - "closing"
  #   - "resize_{model_type}"
  #   - "min_max_normalize"
  # If false, equivalent to:
  # preprocessing_steps:
  #   - "resize_{model_type}"
  #   - "min_max_normalize"

train_dataset:
  remove_previously_processed: true
  dataset_type: "synthetic"  # Can be "real" or "synthetic"
  # folder_name: "train"  # Picks all the images from this folder and the .csv file with the same name.

val_dataset:
  remove_previously_processed: true
  dataset_type: "real"  # Can be "real" or "synthetic"
  folder_name: "validation"
  # data_path: "/path/to/data/raw"  # This will override DATA_RAW_PATH if specified

dataloader:
  batch_size: 32
  shuffle: true
  num_workers: 4
  steps_per_epoch: 100  # If any of the datasets' types is "synthetic".
