trainer:
  epochs: 10000
  verbose: true

model:
  model_type: "resnettransformer"  # Can be "resnet", "efficientnet" or "resnettransformer"
  initial_filters: 48
  multiplier: 2

optimizer:
  learning_rate: 0.0005
  weight_decay: 0.00001

preprocessing:
  use_full_preprocessing: true
  # If true, equivalent to:
  # preprocessing_steps:
  #   - "remove_background"
  #   - "to_grayscale"
  #   - "closing"
  #   - "resize_resnet"
  # If false, equivalent to:
  # preprocessing_steps:
  #   - "resize_resnet"

train_dataset:
  remove_previously_processed: false
  dataset_type: "synthetic"  # Can be "real" or "synthetic"
  folder_name: "train"  # Picks all the images from this folder and the .csv file with the same name.
  save_preprocessed: false
val_dataset:
  remove_previously_processed: true
  dataset_type: "real"  # Can be "real" or "synthetic"
  folder_name: "validation"  # Picks all the images from this folder and the .csv file with the same name.
  # data_path: "/path/to/data/raw"  # This will override DATA_RAW_PATH if specified

dataloader:
  batch_size: 64
  shuffle: true
  num_workers: 0
  steps_per_epoch: 50
